/* Generated by tools/prepare_xscreensaver.py. */
#include "screenhackI.h"
extern struct xscreensaver_function_table attraction_xscreensaver_function_table;
extern struct xscreensaver_function_table blitspin_xscreensaver_function_table;
extern struct xscreensaver_function_table bouboule_xscreensaver_function_table;
extern struct xscreensaver_function_table braid_xscreensaver_function_table;
extern struct xscreensaver_function_table decayscreen_xscreensaver_function_table;
extern struct xscreensaver_function_table deco_xscreensaver_function_table;
extern struct xscreensaver_function_table drift_xscreensaver_function_table;
extern struct xscreensaver_function_table flame_xscreensaver_function_table;
extern struct xscreensaver_function_table galaxy_xscreensaver_function_table;
extern struct xscreensaver_function_table grav_xscreensaver_function_table;
extern struct xscreensaver_function_table greynetic_xscreensaver_function_table;
extern struct xscreensaver_function_table halo_xscreensaver_function_table;
extern struct xscreensaver_function_table helix_xscreensaver_function_table;
extern struct xscreensaver_function_table hopalong_xscreensaver_function_table;
extern struct xscreensaver_function_table ifs_xscreensaver_function_table;
extern struct xscreensaver_function_table imsmap_xscreensaver_function_table;
extern struct xscreensaver_function_table julia_xscreensaver_function_table;
extern struct xscreensaver_function_table kaleidescope_xscreensaver_function_table;
extern struct xscreensaver_function_table maze_xscreensaver_function_table;
extern struct xscreensaver_function_table moire_xscreensaver_function_table;
extern struct xscreensaver_function_table noseguy_xscreensaver_function_table;
extern struct xscreensaver_function_table pedal_xscreensaver_function_table;
extern struct xscreensaver_function_table penrose_xscreensaver_function_table;
extern struct xscreensaver_function_table pyro_xscreensaver_function_table;
extern struct xscreensaver_function_table qix_xscreensaver_function_table;
extern struct xscreensaver_function_table rocks_xscreensaver_function_table;
extern struct xscreensaver_function_table rorschach_xscreensaver_function_table;
extern struct xscreensaver_function_table sierpinski_xscreensaver_function_table;
extern struct xscreensaver_function_table slidescreen_xscreensaver_function_table;
extern struct xscreensaver_function_table slip_xscreensaver_function_table;
extern struct xscreensaver_function_table strange_xscreensaver_function_table;
extern struct xscreensaver_function_table swirl_xscreensaver_function_table;
extern struct xscreensaver_function_table goop_xscreensaver_function_table;
extern struct xscreensaver_function_table starfish_xscreensaver_function_table;
extern struct xscreensaver_function_table munch_xscreensaver_function_table;
extern struct xscreensaver_function_table fadeplot_xscreensaver_function_table;
extern struct xscreensaver_function_table rdbomb_xscreensaver_function_table;
extern struct xscreensaver_function_table coral_xscreensaver_function_table;
extern struct xscreensaver_function_table mountain_xscreensaver_function_table;
extern struct xscreensaver_function_table triangle_xscreensaver_function_table;
extern struct xscreensaver_function_table xjack_xscreensaver_function_table;
extern struct xscreensaver_function_table xlyap_xscreensaver_function_table;
extern struct xscreensaver_function_table cynosure_xscreensaver_function_table;
extern struct xscreensaver_function_table moire2_xscreensaver_function_table;
extern struct xscreensaver_function_table flow_xscreensaver_function_table;
extern struct xscreensaver_function_table epicycle_xscreensaver_function_table;
extern struct xscreensaver_function_table interference_xscreensaver_function_table;
extern struct xscreensaver_function_table truchet_xscreensaver_function_table;
extern struct xscreensaver_function_table bsod_xscreensaver_function_table;
extern struct xscreensaver_function_table crystal_xscreensaver_function_table;
extern struct xscreensaver_function_table discrete_xscreensaver_function_table;
extern struct xscreensaver_function_table distort_xscreensaver_function_table;
extern struct xscreensaver_function_table kumppa_xscreensaver_function_table;
extern struct xscreensaver_function_table demon_xscreensaver_function_table;
extern struct xscreensaver_function_table loop_xscreensaver_function_table;
extern struct xscreensaver_function_table penetrate_xscreensaver_function_table;
extern struct xscreensaver_function_table deluxe_xscreensaver_function_table;
extern struct xscreensaver_function_table compass_xscreensaver_function_table;
extern struct xscreensaver_function_table squiral_xscreensaver_function_table;
extern struct xscreensaver_function_table xflame_xscreensaver_function_table;
extern struct xscreensaver_function_table wander_xscreensaver_function_table;
extern struct xscreensaver_function_table spotlight_xscreensaver_function_table;
extern struct xscreensaver_function_table phosphor_xscreensaver_function_table;
extern struct xscreensaver_function_table xmatrix_xscreensaver_function_table;
extern struct xscreensaver_function_table petri_xscreensaver_function_table;
extern struct xscreensaver_function_table shadebobs_xscreensaver_function_table;
extern struct xscreensaver_function_table ccurve_xscreensaver_function_table;
extern struct xscreensaver_function_table blaster_xscreensaver_function_table;
extern struct xscreensaver_function_table bumps_xscreensaver_function_table;
extern struct xscreensaver_function_table ripples_xscreensaver_function_table;
extern struct xscreensaver_function_table xspirograph_xscreensaver_function_table;
extern struct xscreensaver_function_table nerverot_xscreensaver_function_table;
extern struct xscreensaver_function_table xrayswarm_xscreensaver_function_table;
extern struct xscreensaver_function_table zoom_xscreensaver_function_table;
extern struct xscreensaver_function_table whirlwindwarp_xscreensaver_function_table;
extern struct xscreensaver_function_table rotzoomer_xscreensaver_function_table;
extern struct xscreensaver_function_table speedmine_xscreensaver_function_table;
extern struct xscreensaver_function_table vermiculate_xscreensaver_function_table;
extern struct xscreensaver_function_table twang_xscreensaver_function_table;
extern struct xscreensaver_function_table apollonian_xscreensaver_function_table;
extern struct xscreensaver_function_table euler2d_xscreensaver_function_table;
extern struct xscreensaver_function_table polyominoes_xscreensaver_function_table;
extern struct xscreensaver_function_table fluidballs_xscreensaver_function_table;
extern struct xscreensaver_function_table anemone_xscreensaver_function_table;
extern struct xscreensaver_function_table halftone_xscreensaver_function_table;
extern struct xscreensaver_function_table metaballs_xscreensaver_function_table;
extern struct xscreensaver_function_table eruption_xscreensaver_function_table;
extern struct xscreensaver_function_table popsquares_xscreensaver_function_table;
extern struct xscreensaver_function_table barcode_xscreensaver_function_table;
extern struct xscreensaver_function_table piecewise_xscreensaver_function_table;
extern struct xscreensaver_function_table cloudlife_xscreensaver_function_table;
extern struct xscreensaver_function_table fontglide_xscreensaver_function_table;
extern struct xscreensaver_function_table apple2_xscreensaver_function_table;
extern struct xscreensaver_function_table xanalogtv_xscreensaver_function_table;
extern struct xscreensaver_function_table pong_xscreensaver_function_table;
extern struct xscreensaver_function_table filmleader_xscreensaver_function_table;
extern struct xscreensaver_function_table wormhole_xscreensaver_function_table;
extern struct xscreensaver_function_table pacman_xscreensaver_function_table;
extern struct xscreensaver_function_table fuzzyflakes_xscreensaver_function_table;
extern struct xscreensaver_function_table anemotaxis_xscreensaver_function_table;
extern struct xscreensaver_function_table memscroller_xscreensaver_function_table;
extern struct xscreensaver_function_table substrate_xscreensaver_function_table;
extern struct xscreensaver_function_table intermomentary_xscreensaver_function_table;
extern struct xscreensaver_function_table fireworkx_xscreensaver_function_table;
extern struct xscreensaver_function_table fiberlamp_xscreensaver_function_table;
extern struct xscreensaver_function_table boxfit_xscreensaver_function_table;
extern struct xscreensaver_function_table interaggregate_xscreensaver_function_table;
extern struct xscreensaver_function_table celtic_xscreensaver_function_table;
extern struct xscreensaver_function_table cwaves_xscreensaver_function_table;
extern struct xscreensaver_function_table m6502_xscreensaver_function_table;
extern struct xscreensaver_function_table abstractile_xscreensaver_function_table;
extern struct xscreensaver_function_table lcdscrub_xscreensaver_function_table;
extern struct xscreensaver_function_table hexadrop_xscreensaver_function_table;
extern struct xscreensaver_function_table tessellimage_xscreensaver_function_table;
extern struct xscreensaver_function_table binaryring_xscreensaver_function_table;
extern struct xscreensaver_function_table glitchpeg_xscreensaver_function_table;
extern struct xscreensaver_function_table vfeedback_xscreensaver_function_table;
extern struct xscreensaver_function_table scooter_xscreensaver_function_table;
extern struct xscreensaver_function_table marbling_xscreensaver_function_table;
extern struct xscreensaver_function_table binaryhorizon_xscreensaver_function_table;
extern struct xscreensaver_function_table droste_xscreensaver_function_table;
extern struct xscreensaver_function_table ant_xscreensaver_function_table;
extern struct xscreensaver_function_table bubbles_xscreensaver_function_table;
extern struct xscreensaver_function_table critical_xscreensaver_function_table;
extern struct xscreensaver_function_table flag_xscreensaver_function_table;
extern struct xscreensaver_function_table forest_xscreensaver_function_table;
extern struct xscreensaver_function_table hyperball_xscreensaver_function_table;
extern struct xscreensaver_function_table hypercube_xscreensaver_function_table;
extern struct xscreensaver_function_table laser_xscreensaver_function_table;
extern struct xscreensaver_function_table lightning_xscreensaver_function_table;
extern struct xscreensaver_function_table lisa_xscreensaver_function_table;
extern struct xscreensaver_function_table lissie_xscreensaver_function_table;
extern struct xscreensaver_function_table lmorph_xscreensaver_function_table;
extern struct xscreensaver_function_table rotor_xscreensaver_function_table;
extern struct xscreensaver_function_table sphere_xscreensaver_function_table;
extern struct xscreensaver_function_table spiral_xscreensaver_function_table;
extern struct xscreensaver_function_table t3d_xscreensaver_function_table;
extern struct xscreensaver_function_table vines_xscreensaver_function_table;
extern struct xscreensaver_function_table whirlygig_xscreensaver_function_table;
extern struct xscreensaver_function_table worm_xscreensaver_function_table;
extern struct xscreensaver_function_table xsublim_xscreensaver_function_table;
extern struct xscreensaver_function_table juggle_xscreensaver_function_table;
extern struct xscreensaver_function_table thornbird_xscreensaver_function_table;
extern struct xscreensaver_function_table munch_xscreensaver_function_table;
struct xscreensaver_function_table *const xs_modules[] = {
  &attraction_xscreensaver_function_table,
  &blitspin_xscreensaver_function_table,
  &bouboule_xscreensaver_function_table,
  &braid_xscreensaver_function_table,
  &decayscreen_xscreensaver_function_table,
  &deco_xscreensaver_function_table,
  &drift_xscreensaver_function_table,
  &flame_xscreensaver_function_table,
  &galaxy_xscreensaver_function_table,
  &grav_xscreensaver_function_table,
  &greynetic_xscreensaver_function_table,
  &halo_xscreensaver_function_table,
  &helix_xscreensaver_function_table,
  &hopalong_xscreensaver_function_table,
  &ifs_xscreensaver_function_table,
  &imsmap_xscreensaver_function_table,
  &julia_xscreensaver_function_table,
  &kaleidescope_xscreensaver_function_table,
  &maze_xscreensaver_function_table,
  &moire_xscreensaver_function_table,
  &noseguy_xscreensaver_function_table,
  &pedal_xscreensaver_function_table,
  &penrose_xscreensaver_function_table,
  &pyro_xscreensaver_function_table,
  &qix_xscreensaver_function_table,
  &rocks_xscreensaver_function_table,
  &rorschach_xscreensaver_function_table,
  &sierpinski_xscreensaver_function_table,
  &slidescreen_xscreensaver_function_table,
  &slip_xscreensaver_function_table,
  &strange_xscreensaver_function_table,
  &swirl_xscreensaver_function_table,
  &goop_xscreensaver_function_table,
  &starfish_xscreensaver_function_table,
  &munch_xscreensaver_function_table,
  &fadeplot_xscreensaver_function_table,
  &rdbomb_xscreensaver_function_table,
  &coral_xscreensaver_function_table,
  &mountain_xscreensaver_function_table,
  &triangle_xscreensaver_function_table,
  &xjack_xscreensaver_function_table,
  &xlyap_xscreensaver_function_table,
  &cynosure_xscreensaver_function_table,
  &moire2_xscreensaver_function_table,
  &flow_xscreensaver_function_table,
  &epicycle_xscreensaver_function_table,
  &interference_xscreensaver_function_table,
  &truchet_xscreensaver_function_table,
  &bsod_xscreensaver_function_table,
  &crystal_xscreensaver_function_table,
  &discrete_xscreensaver_function_table,
  &distort_xscreensaver_function_table,
  &kumppa_xscreensaver_function_table,
  &demon_xscreensaver_function_table,
  &loop_xscreensaver_function_table,
  &penetrate_xscreensaver_function_table,
  &deluxe_xscreensaver_function_table,
  &compass_xscreensaver_function_table,
  &squiral_xscreensaver_function_table,
  &xflame_xscreensaver_function_table,
  &wander_xscreensaver_function_table,
  &spotlight_xscreensaver_function_table,
  &phosphor_xscreensaver_function_table,
  &xmatrix_xscreensaver_function_table,
  &petri_xscreensaver_function_table,
  &shadebobs_xscreensaver_function_table,
  &ccurve_xscreensaver_function_table,
  &blaster_xscreensaver_function_table,
  &bumps_xscreensaver_function_table,
  &ripples_xscreensaver_function_table,
  &xspirograph_xscreensaver_function_table,
  &nerverot_xscreensaver_function_table,
  &xrayswarm_xscreensaver_function_table,
  &zoom_xscreensaver_function_table,
  &whirlwindwarp_xscreensaver_function_table,
  &rotzoomer_xscreensaver_function_table,
  &speedmine_xscreensaver_function_table,
  &vermiculate_xscreensaver_function_table,
  &twang_xscreensaver_function_table,
  &apollonian_xscreensaver_function_table,
  &euler2d_xscreensaver_function_table,
  &polyominoes_xscreensaver_function_table,
  &fluidballs_xscreensaver_function_table,
  &anemone_xscreensaver_function_table,
  &halftone_xscreensaver_function_table,
  &metaballs_xscreensaver_function_table,
  &eruption_xscreensaver_function_table,
  &popsquares_xscreensaver_function_table,
  &barcode_xscreensaver_function_table,
  &piecewise_xscreensaver_function_table,
  &cloudlife_xscreensaver_function_table,
  &fontglide_xscreensaver_function_table,
  &apple2_xscreensaver_function_table,
  &xanalogtv_xscreensaver_function_table,
  &pong_xscreensaver_function_table,
  &filmleader_xscreensaver_function_table,
  &wormhole_xscreensaver_function_table,
  &pacman_xscreensaver_function_table,
  &fuzzyflakes_xscreensaver_function_table,
  &anemotaxis_xscreensaver_function_table,
  &memscroller_xscreensaver_function_table,
  &substrate_xscreensaver_function_table,
  &intermomentary_xscreensaver_function_table,
  &fireworkx_xscreensaver_function_table,
  &fiberlamp_xscreensaver_function_table,
  &boxfit_xscreensaver_function_table,
  &interaggregate_xscreensaver_function_table,
  &celtic_xscreensaver_function_table,
  &cwaves_xscreensaver_function_table,
  &m6502_xscreensaver_function_table,
  &abstractile_xscreensaver_function_table,
  &lcdscrub_xscreensaver_function_table,
  &hexadrop_xscreensaver_function_table,
  &tessellimage_xscreensaver_function_table,
  &binaryring_xscreensaver_function_table,
  &glitchpeg_xscreensaver_function_table,
  &vfeedback_xscreensaver_function_table,
  &scooter_xscreensaver_function_table,
  &marbling_xscreensaver_function_table,
  &binaryhorizon_xscreensaver_function_table,
  &droste_xscreensaver_function_table,
  &ant_xscreensaver_function_table,
  &bubbles_xscreensaver_function_table,
  &critical_xscreensaver_function_table,
  &flag_xscreensaver_function_table,
  &forest_xscreensaver_function_table,
  &hyperball_xscreensaver_function_table,
  &hypercube_xscreensaver_function_table,
  &laser_xscreensaver_function_table,
  &lightning_xscreensaver_function_table,
  &lisa_xscreensaver_function_table,
  &lissie_xscreensaver_function_table,
  &lmorph_xscreensaver_function_table,
  &rotor_xscreensaver_function_table,
  &sphere_xscreensaver_function_table,
  &spiral_xscreensaver_function_table,
  &t3d_xscreensaver_function_table,
  &vines_xscreensaver_function_table,
  &whirlygig_xscreensaver_function_table,
  &worm_xscreensaver_function_table,
  &xsublim_xscreensaver_function_table,
  &juggle_xscreensaver_function_table,
  &thornbird_xscreensaver_function_table,
  &munch_xscreensaver_function_table,
};
const unsigned xs_module_count = sizeof(xs_modules)/sizeof(xs_modules[0]);
const char *const xs_module_names[] = {
  "attraction",
  "blitspin",
  "bouboule",
  "braid",
  "decayscreen",
  "deco",
  "drift",
  "flame",
  "galaxy",
  "grav",
  "greynetic",
  "halo",
  "helix",
  "hopalong",
  "ifs",
  "imsmap",
  "julia",
  "kaleidescope",
  "maze",
  "moire",
  "noseguy",
  "pedal",
  "penrose",
  "pyro",
  "qix",
  "rocks",
  "rorschach",
  "sierpinski",
  "slidescreen",
  "slip",
  "strange",
  "swirl",
  "goop",
  "starfish",
  "munch",
  "fadeplot",
  "rdbomb",
  "coral",
  "mountain",
  "triangle",
  "xjack",
  "xlyap",
  "cynosure",
  "moire2",
  "flow",
  "epicycle",
  "interference",
  "truchet",
  "bsod",
  "crystal",
  "discrete",
  "distort",
  "kumppa",
  "demon",
  "loop",
  "penetrate",
  "deluxe",
  "compass",
  "squiral",
  "xflame",
  "wander",
  "spotlight",
  "phosphor",
  "xmatrix",
  "petri",
  "shadebobs",
  "ccurve",
  "blaster",
  "bumps",
  "ripples",
  "xspirograph",
  "nerverot",
  "xrayswarm",
  "zoom",
  "whirlwindwarp",
  "rotzoomer",
  "speedmine",
  "vermiculate",
  "twang",
  "apollonian",
  "euler2d",
  "polyominoes",
  "fluidballs",
  "anemone",
  "halftone",
  "metaballs",
  "eruption",
  "popsquares",
  "barcode",
  "piecewise",
  "cloudlife",
  "fontglide",
  "apple2",
  "xanalogtv",
  "pong",
  "filmleader",
  "wormhole",
  "pacman",
  "fuzzyflakes",
  "anemotaxis",
  "memscroller",
  "substrate",
  "intermomentary",
  "fireworkx",
  "fiberlamp",
  "boxfit",
  "interaggregate",
  "celtic",
  "cwaves",
  "m6502",
  "abstractile",
  "lcdscrub",
  "hexadrop",
  "tessellimage",
  "binaryring",
  "glitchpeg",
  "vfeedback",
  "scooter",
  "marbling",
  "binaryhorizon",
  "droste",
  "ant",
  "bubbles",
  "critical",
  "flag",
  "forest",
  "hyperball",
  "hypercube",
  "laser",
  "lightning",
  "lisa",
  "lissie",
  "lmorph",
  "rotor",
  "sphere",
  "spiral",
  "t3d",
  "vines",
  "whirlygig",
  "worm",
  "xsublim",
  "juggle",
  "thornbird",
  "mismunch",
};
