"""Generate board asset headers and the registry from the pinned upstream tree."""
import json, re, struct
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
up = root / 'third_party/xscreensaver'
manifest = json.loads((up / 'inventory.json').read_text())
sources = [up / e['source'] for e in manifest['cpu']]
sources += [up / 'hacks/apple2.c', up / 'hacks/analogtv.c', up / 'hacks/bubbles-default.c']
headers = set()
for source in sources:
    headers.update(re.findall(r'"images/gen/([^"]+)"', source.read_text(encoding='utf-8')))
gen = up / 'hacks/images/gen'
gen.mkdir(exist_ok=True)
assets = ['/* Generated shared asset pool; source licenses remain in the upstream tree. */', '#include "config.h"']
asset_bytes = 0
for header in sorted(headers):
    stem = header.removesuffix('_png.h')
    path = next((up / 'hacks/images').rglob(stem + '.png'))
    im = Image.open(path).convert('RGBA')
    if not any(x in stem for x in ['font','matrix','nose','logo','pacman']):
        im.thumbnail((200,320), Image.Resampling.LANCZOS)
    # XSR1: little-endian dimensions, then runs of (u16 length, ARGB u32).
    pixels = [((a << 24) | (r << 16) | (g << 8) | b) for r,g,b,a in im.getdata()]
    data = bytearray(b'XSR1' + struct.pack('<HH', *im.size))
    i = 0
    while i < len(pixels):
        n = 1
        while i+n < len(pixels) and pixels[i+n] == pixels[i] and n < 65535:
            n += 1
        data.extend(struct.pack('<HI', n, pixels[i]))
        i += n
    symbol = re.sub(r'[^a-zA-Z0-9_]', '_', stem) + '_png'
    if symbol[0].isdigit():
        symbol = '_' + symbol
    # Photos use packed RGB565 plus a transparency bit; choose the smaller representation.
    packed = bytearray(b'XSB1' + struct.pack('<HH', *im.size))
    packed.extend(b''.join(struct.pack('<H', ((p>>19)&31)<<11 | ((p>>10)&63)<<5 | ((p>>3)&31)) for p in pixels))
    packed.extend(bytes(sum((1 << bit) if i+bit<len(pixels) and pixels[i+bit]>>24 else 0 for bit in range(8)) for i in range(0,len(pixels),8)))
    if len(packed) < len(data): data = packed
    notice = '/* Generated from upstream ' + str(path.relative_to(up)).replace('\\','/') + '; preserves its license. */'
    lines = [notice, 'const unsigned char ' + symbol + '[] XS_ASSET = {']
    lines += [','.join(str(x) for x in data[i:i+32]) + ',' for i in range(0,len(data),32)]
    lines += ['};', '']
    assets.extend(lines)
    asset_bytes += len(data)
    (gen / header).write_text(notice + '\nextern const unsigned char ' + symbol + '[' + str(len(data)) + '];\n')
if asset_bytes > 1536 * 1024:
    raise RuntimeError(f'Assets exceed the MRAM budget: {asset_bytes} bytes')
(root/'M55_HP/xs_port/assets.c').write_text('\n'.join(assets))
asm = sorted((up/'hacks/images/m6502').glob('*.asm'))
(up/'hacks/m6502.h').write_text(',\n'.join(json.dumps(re.sub(r'[ \t]*;[^\n]*', '', p.read_text(encoding='utf-8'))) for p in asm) + '\n')
font = Image.open(up/'hacks/images/6x10font.png').convert('RGBA')
fontlines = ['/* Bitmap font from upstream 6x10font.png. */', '#include "xs_internal.h"', 'const unsigned char xs_font_bits[256][10] = {']
for c in range(256):
    rows = [sum(1<<x for x in range(7) if font.getpixel((c*7+x,y))[3] and sum(font.getpixel((c*7+x,y))[:3])<384) for y in range(10)]
    fontlines.append('  {'+','.join(str(x) for x in rows)+'},')
fontlines += ['};','']
(root/'M55_HP/xs_port/font.c').write_text('\n'.join(fontlines))
# Bundled screen/image input uses the upstream SOM illustration.
(root/'M55_HP/xs_port/picture.c').write_text('#include "xs_internal.h"\n#include "images/gen/som_png.h"\nconst unsigned char *const xs_picture=som_png;\nconst size_t xs_picture_size=sizeof(som_png);\n')
registry = ['/* Generated by tools/prepare_xscreensaver.py. */', '#include "screenhackI.h"']
symbols = []
for e in manifest['cpu']:
    text = (up/e['source']).read_text(encoding='utf-8')
    calls = re.findall(r'XSCREENSAVER_MODULE(?:_2)?\s*\(\s*"[^"]+"\s*,\s*(\w+)', text)
    if not calls:
        calls = re.findall(r'XSCREENSAVER_MODULE\s*\(\s*(\w+)', text)
    if not calls:
        if e['name']=='xsublim': calls=['xsublim']
        else: raise RuntimeError('No module table: ' + e['name'])
    symbol = calls[-1] + '_xscreensaver_function_table'
    symbols.append(symbol)
    registry.append('extern struct xscreensaver_function_table ' + symbol + ';')
registry += ['struct xscreensaver_function_table *const xs_modules[] = {']
registry += ['  &' + s + ',' for s in symbols]
registry += ['};', 'const unsigned xs_module_count = sizeof(xs_modules)/sizeof(xs_modules[0]);',
             'const char *const xs_module_names[] = {']
registry += ['  "' + e['name'] + '",' for e in manifest['cpu']]
registry += ['};', '']
(root/'M55_HP/xs_port/registry.c').write_text('\n'.join(registry))
print(f'{len(headers)} shared assets ({asset_bytes} bytes), {len(symbols)} registry entries')
