/* Read and evaluate inside functions.exec. No Node/shell board access.
 * Read runtime-stress-progress.json separately and restore xs_sustained_final,
 * xs_final_stress_host and xs_final_targeted_board from it before sampling.
 * Do not reset the board or request a saver during natural cycling. */
const stressHelpers = {
  "xs_decode_words": "r => { const t=r.content.filter(x=>x.type===\"text\").map(x=>x.text).join(\"\\n\");const b=[...t.matchAll(/0x[0-9a-f]+: ([0-9a-f ]+)/gi)].flatMap(m=>m[1].trim().split(/\\s+/).map(x=>parseInt(x,16)));return Array.from({length:b.length/4},(_,i)=>(b[i*4]+b[i*4+1]*256+b[i*4+2]*65536+b[i*4+3]*16777216)>>>0); }",
  "xs_read_state": "async () => {\nconst s=await tools.mcp__cmsis_developer_assistant__get_session_status({});\nconst status=s.content.filter(c=>c.type===\"text\").map(c=>c.text).join(\"\\n\");\nif(!status.includes(\"State: running\")&&!status.includes(\"State: stopped\")){text(s);return false;}\nif(status.includes(\"State: running\")){\n const p=await tools.mcp__cmsis_developer_assistant__pause_execution({timeoutMs:10000});\n if(p.isError){text(p);return false;}\n}\nconst d=eval(load(\"xs_decode_words\"));\nconst r1=await tools.mcp__cmsis_developer_assistant__read_memory({address:load(\"xs_board_addresses\").ms_ticks,length:24});\nif(r1.isError){text(r1);return false;}\nconst r2=await tools.mcp__cmsis_developer_assistant__read_memory({address:load(\"xs_board_addresses\").xs_last_error,length:32});\nif(r2.isError){text(r2);return false;}\nconst r3=await tools.mcp__cmsis_developer_assistant__read_memory({address:load(\"xs_board_addresses\").xs_memory_peak,length:4});if(r3.isError){text(r3);return false;}const a=d(r1),b=d(r2),peak=d(r3)[0];\nconst fault=await tools.mcp__cmsis_developer_assistant__get_fault_info({});\nif(fault.isError){text(fault);return false;}\nconst faultText=fault.content.filter(c=>c.type===\"text\").map(c=>c.text).join(\"\\n\");\nconst faultStatus=Object.fromEntries([\"HFSR\",\"MMFSR\",\"BFSR\",\"UFSR\"].map(n=>[n,parseInt(faultText.match(new RegExp(n+\"\\\\s*=\\\\s*0x([0-9a-f]+)\",\"i\"))?.[1]??\"ffffffff\",16)]));\nconst sample={utc:(await tools.clock__curr_time({})).current_time,fault_status:faultStatus,ms_ticks:a[0],app_stage:a[1],display_events:a[2],app_error:a[3],app_service_error:a[4],frames_presented:a[5],xs_last_error:b[0],xs_failures:b[2],xs_current_saver:b[5],next_frame:b[6],started:b[7],xs_memory_peak:peak};\nconst samples=load(\"xs_board_samples\"); const last=samples.at(-1); samples.push(sample);store(\"xs_board_samples\",samples);\nif(Object.values(faultStatus).some(v=>v!==0)||sample.app_stage!==8||sample.app_error||sample.app_service_error||sample.display_events||sample.xs_failures){text(\"Inspection needed; left halted.\");return false;}\nreturn sample;\n}",
  "xs_board_addresses": {
    "ms_ticks": "0x2000a258",
    "app_stage": "0x2000a25c",
    "xs_last_error": "0x2000a4d8",
    "xs_current_saver": "0x2000a4ec",
    "xs_memory_peak": "0x2000a40c",
    "started": "0x2000a4f4",
    "xs_cycle_enabled": "0x2000001c",
    "xs_requested_saver": "0x20000020",
    "display_events": "0x2000a260",
    "app_error": "0x2000a264",
    "app_service_error": "0x2000a268",
    "frames_presented": "0x2000a26c",
    "xs_failures": "0x2000a4e0",
    "next_frame": "0x2000a4f0"
  },
  "xs_names": [
    "attraction",
    "blitspin",
    "bouboule",
    "braid",
    "decayscreen",
    "deco",
    "drift",
    "flame",
    "galaxy",
    "grav",
    "greynetic",
    "halo",
    "helix",
    "hopalong",
    "ifs",
    "imsmap",
    "julia",
    "kaleidescope",
    "maze",
    "moire",
    "noseguy",
    "pedal",
    "penrose",
    "pyro",
    "qix",
    "rocks",
    "rorschach",
    "sierpinski",
    "slidescreen",
    "slip",
    "strange",
    "swirl",
    "goop",
    "starfish",
    "munch",
    "fadeplot",
    "rdbomb",
    "coral",
    "mountain",
    "triangle",
    "xjack",
    "xlyap",
    "cynosure",
    "moire2",
    "flow",
    "epicycle",
    "interference",
    "truchet",
    "bsod",
    "crystal",
    "discrete",
    "distort",
    "kumppa",
    "demon",
    "loop",
    "penetrate",
    "deluxe",
    "compass",
    "squiral",
    "xflame",
    "wander",
    "spotlight",
    "phosphor",
    "xmatrix",
    "petri",
    "shadebobs",
    "ccurve",
    "blaster",
    "bumps",
    "ripples",
    "xspirograph",
    "nerverot",
    "xrayswarm",
    "zoom",
    "whirlwindwarp",
    "rotzoomer",
    "speedmine",
    "vermiculate",
    "twang",
    "apollonian",
    "euler2d",
    "polyominoes",
    "fluidballs",
    "anemone",
    "halftone",
    "metaballs",
    "eruption",
    "popsquares",
    "barcode",
    "piecewise",
    "cloudlife",
    "fontglide",
    "apple2",
    "xanalogtv",
    "pong",
    "filmleader",
    "wormhole",
    "pacman",
    "fuzzyflakes",
    "anemotaxis",
    "memscroller",
    "substrate",
    "intermomentary",
    "fireworkx",
    "fiberlamp",
    "boxfit",
    "interaggregate",
    "celtic",
    "cwaves",
    "m6502",
    "abstractile",
    "lcdscrub",
    "hexadrop",
    "tessellimage",
    "binaryring",
    "glitchpeg",
    "vfeedback",
    "scooter",
    "marbling",
    "binaryhorizon",
    "droste",
    "ant",
    "bubbles",
    "critical",
    "flag",
    "forest",
    "hyperball",
    "hypercube",
    "laser",
    "lightning",
    "lisa",
    "lissie",
    "lmorph",
    "rotor",
    "sphere",
    "spiral",
    "t3d",
    "vines",
    "whirlygig",
    "worm",
    "xsublim",
    "juggle",
    "thornbird",
    "mismunch",
    "webcollage",
    "vidwhacker"
  ],
  "xs_monitor_sustained": "async () => {\n const r=load(\"xs_sustained_final\");\n const previous=r.samples.at(-1);\n const sample=await eval(load(\"xs_read_state\"))();\n if(!sample){r.passed=false;r.stopped_utc=(await tools.clock__curr_time({})).current_time;store(\"xs_sustained_final\",r);return {healthy:false};}\n const delta=(sample.xs_current_saver-previous.xs_current_saver+146)%146;\n const elapsed=(sample.ms_ticks-previous.ms_ticks)>>>0;\n const frames=(sample.frames_presented-previous.frames_presented)>>>0;\n r.samples.push(sample);\n if(sample.xs_last_error || !frames || !elapsed || delta>12) {store(\"xs_sustained_final\",r);text(sample);return {healthy:false,reason:\"Status/presentation/sequence inspection needed\"};}\n r.transitions+=delta;r.passed=r.transitions>=292;\n store(\"xs_sustained_final\",r);\n if(r.passed){r.end_utc=sample.utc;store(\"xs_sustained_final\",r);}\n const run=await tools.mcp__cmsis_developer_assistant__continue_execution({timeoutMs:1000});\n if(run.isError){text(run);return {healthy:false};}\n return {healthy:true,transitions:r.transitions,rotations:Math.floor(r.transitions/146),current:sample.xs_current_saver,name:load(\"xs_names\")[sample.xs_current_saver],frames,elapsed_ms:elapsed,passed:r.passed};\n}",
  "xs_save_stress": "async () => {\n const content=JSON.stringify({updated_utc:(await tools.clock__curr_time({})).current_time,host:load(\"xs_final_stress_host\"),targeted_board:load(\"xs_final_targeted_board\"),sustained_board:load(\"xs_sustained_final\")},null,2);\n const old=load(\"xs_stress_saved_content\");\n const patch=old ? \"*** Begin Patch\\n*** Update File: third_party/xscreensaver/runtime-stress-progress.json\\n@@\\n-\"+old.split(\"\\n\").join(\"\\n-\")+\"\\n+\"+content.split(\"\\n\").join(\"\\n+\")+\"\\n*** End Patch\" : \"*** Begin Patch\\n*** Add File: third_party/xscreensaver/runtime-stress-progress.json\\n+\"+content.split(\"\\n\").join(\"\\n+\")+\"\\n*** End Patch\";\n const result=await tools.apply_patch(patch);\n store(\"xs_stress_saved_content\",content);return result;\n}",
  "xs_board_samples": []
};
for (const [key,value] of Object.entries(stressHelpers)) store(key,value);
